feat: Add new file and configuration
zeabix-cloud-native/k6-prometheus-orb pull request #1
Opened 2023-01-16 09:17 UTC by amornc

About this orb:

- use image: loadimpact/k6:latest
- fill 'remote_url' (prometheus server full url without '/api/v1/write') 
- fill 'file' script path
- skip_tls_verify: "true" (default)
- save result to artifacts

prerequisite
- env name 'K6_PROMETHEUS_RW_USERNAME' for prometheus user
- env name 'K6_PROMETHEUS_RW_PASSWORD' for prometheus password
- k6 folder (optional)

2023-01-16 09:43 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/k6-prometheus?version=dev:359877f147ca46486e1b859248847a378a6b45e8

2023-01-16 09:44 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/k6-prometheus?version=dev:5a80689ac622869138883930c2dc01c3450b7133

2023-01-16 09:48 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/k6-prometheus?version=dev:bddf9ff475c621bdaef38088ec1213e709672848

2023-01-16 09:50 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/k6-prometheus?version=dev:f6acb41f3f2ead9dad75bdc01459adb6b95246e1

2023-01-16 13:20 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/k6-prometheus?version=dev:d542c35958301c5f5d8c12027d21487e06a04b36

2023-01-16 13:36 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/k6-prometheus?version=dev:13821ac65901d9dd5e30722d1da9da9118919726

2023-01-16 13:42 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/k6-prometheus?version=dev:4a2c9977d4a168d9212785ac61c25131df842769

2023-01-16 13:46 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/k6-prometheus?version=dev:007470732babcdb64a06889089b629cc26e524be

2023-01-16 13:48 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/k6-prometheus?version=dev:762c1462ce375df46dd77917f59b878ced9a8c2a

2023-01-16 13:52 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/k6-prometheus?version=dev:ad3f518eb053f52cadd05c8fca61122903c83f21

2023-01-17 02:44 UTC, puizeabix requested changes
Please see the comments krub

2023-01-17 02:44 UTC, puizeabix commented on src/commands/k6-prometheus.yml
> +    description: "INSECURE SKIP TLS VERIFY"
Incorrect description

2023-01-17 02:44 UTC, puizeabix commented on src/commands/k6-prometheus.yml
> +    description: "INSECURE SKIP TLS VERIFY"
Another question krub, How do we authenticate with prometheus

2023-01-17 04:23 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/k6-prometheus?version=dev:cd89192119184bf24f65a1aff1eb0cf5bb55e4d8

2023-01-17 04:42 UTC, amornc commented on src/commands/k6-prometheus.yml
> +    description: "INSECURE SKIP TLS VERIFY"
> Another question krub, How do we authenticate with prometheus

k6 remote write output only supports basic authen krub.
<img width="893" alt="image" src="https://user-images.githubusercontent.com/46469458/212811629-dc607fba-de89-4952-98f6-224dd801bf9b.png">

2023-01-17 04:52 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/k6-prometheus?version=dev:2a97cd5fc67bfe5d0f432690c53690a150b96d71

2023-01-17 05:28 UTC, amornc commented on src/commands/k6-prometheus.yml
> +    description: "INSECURE SKIP TLS VERIFY"
> Incorrect description

Done krub.

2023-01-18 01:21 UTC, merged

2023-01-18 01:22 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/k6-prometheus?version=dev:328aa0e77d2597e8c4bbcb0801fe6d1412ed52de

2023-01-18 02:44 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/k6-prometheus?version=dev:328aa0e77d2597e8c4bbcb0801fe6d1412ed52de

2023-01-18 02:45 UTC, amornc commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/k6-prometheus?version=1.0.0